name: 'frieza-clean'
description: 'Clean an  3DS Outscale account after the action'
inputs:
  access_key:
    description: 'Access Key'
    required: true
  secret_key:
    description: 'Secret Key'
    required: true
  region:
    description: 'Region'
    required: true
  frieza_version:
    description: 'Access Key'
    required: false
    default: 'latest'
  clean_timeout:
    description: 'Timeout when cleaning all the resources in order not to get stuck'
    required: false
    default: '5m'
  error_on_dirty:
    description: Exit in error when the account is not clean.
    required: false
    default: 'false'
  ignore_cleanup_failure:
    description: Ignore cleanup failures, continue to next step if possible.
    required: false
    default: 'false'
  providers:
    description: 'List of providers (comma-separated: outscale_oapi,outscale_oos,outscale_oks,...).'
    required: false
    default: 'outscale_oapi'
  only_resource_types:
    description: Remove only theses resource types (separated by ','). You can see all resource types in the description of the provider.
    required: false
  exclude_resource_types:
    description: Remove all except theses resource types (separated by ','). You can see all resource types in the description of the provider.
    required: false
runs:
  using: 'node20'
  main: 'index.js'
  post: 'cleanup.js'
