name: 'frieza-clean'
description: 'Clean an  3DS Outscale account after the action'
inputs:
  access_key:
    description: 'Access Key'
    required: true
  secret_key:
    description: 'Secret Key'
    required: true
  region:
    description: 'Region'
    required: true
  frieza_version:
    description: 'Access Key'
    required: false
    default: 'latest'
  clean_timeout:
    description: 'Timeout when cleaning all the resources in order not to get stuck'
    required: false
    default: '5m'
  error_on_dirty:
    description: Exit in error when the account is not clean.
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'index.js'
  post: 'cleanup.js'