name: Credential Scanner

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  cred-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Scan credentials
      uses: outscale/cred-scan@main
      with:
        scan_path: "./"
